SELECT USER
FROM DUAL;
--==>> SCOTT


--○ 실습테이블 생성
CREATE TABLE PRACTICE_SCORE0323
( SID   NUMBER
, NAME  VARCHAR(30)
, KOR   NUMBER(3)
, ENG   NUMBER(3)
, MAT   NUMBER(3)
);
--==>> Table PRACTICE_SCORE0323이(가) 생성되었습니다.

--○ 제약 조건 추가(SID 컬럼에 PK 제약조건 추가)
ALTER TABLE PRACTICE_SCORE0323
ADD CONSTRAINT SCORE0323_SID_PK PRIMARY KEY (SID);
--==>> Table PRACTICE_SCORE0323이(가) 변경되었습니다.


--○ 제약조건 추가(KOR, ENG, MAT 컬럼에 CK 제약조건 추가)
ALTER TABLE PRACTICE_SCORE0323
ADD ( CONSTRAINT SCORE0323_KOR_CK CHECK (KOR BETWEEN 0 AND 100)
    , CONSTRAINT SCORE0323_ENG_CK CHECK (ENG BETWEEN 0 AND 100)
    , CONSTRAINT SCORE0323_MAT_CK CHECK (MAT BETWEEN 0 AND 100) );
--==>> Table PRACTICE_SCORE0323이(가) 변경되었습니다.

--○ 시퀀스 생성
CREATE SEQUENCE SCORE0323SEQ
NOCACHE;
--==>> Sequence SCORE0323SEQ이(가) 생성되었습니다.

--○ 커밋
COMMIT;
--==>> 커밋 완료.

INSERT INTO PRACTICE_SCORE0323(SID, NAME, KOR, ENG, MAT) VALUES (SCORE0323SEQ.NEXTVAL, '신시은', 80, 70, 60)
;

SELECT COUNT(*) AS COUNT FROM PRACTICE_SCORE0323
;

SELECT SID, NAME, KOR, ENG, MAT, KOR+ENG+MAT AS TOT, (KOR+ENG+MAT)/3.0 AS AVG FROM PRACTICE_SCORE0323 ORDER BY SID
;

